- pkg:maven/ro.pippo/pippo-metrics-prometheus@1.10.0
- pkg:maven/ro.pippo/pippo-metrics-prometheus@1.10.0?classifier=sources
- pkg:maven/ro.pippo/pippo-metrics-prometheus@1.11.0
- pkg:maven/ro.pippo/pippo-metrics-prometheus@1.11.0?classifier=sources
- pkg:maven/ro.pippo/pippo-metrics-prometheus@1.12.0
- pkg:maven/ro.pippo/pippo-metrics-prometheus@1.12.0?classifier=sources
- pkg:maven/ro.pippo/pippo-metrics-prometheus@1.13.0
- pkg:maven/ro.pippo/pippo-metrics-prometheus@1.13.0?classifier=sources
- pkg:maven/ro.pippo/pippo-metrics-prometheus@1.13.1
- pkg:maven/ro.pippo/pippo-metrics-prometheus@1.13.1?classifier=sources
- pkg:maven/ro.pippo/pippo-metrics-prometheus@1.14.0
- pkg:maven/ro.pippo/pippo-metrics-prometheus@1.14.0?classifier=sources
