- pkg:maven/com.azure.spring/spring-cloud-azure-docker-compose@5.16.0?classifier=sources
- pkg:maven/com.azure.spring/spring-cloud-azure-docker-compose@5.17.0?classifier=sources
- pkg:maven/com.azure.spring/spring-cloud-azure-docker-compose@5.17.1?classifier=sources
- pkg:maven/com.azure.spring/spring-cloud-azure-docker-compose@5.18.0?classifier=sources
- pkg:maven/com.azure.spring/spring-cloud-azure-docker-compose@5.19.0?classifier=sources
