- pkg:maven/com.tencent.polaris/stat-prometheus@1.0.0
- pkg:maven/com.tencent.polaris/stat-prometheus@1.0.0?classifier=sources
- pkg:maven/com.tencent.polaris/stat-prometheus@1.1.0
- pkg:maven/com.tencent.polaris/stat-prometheus@1.1.0?classifier=sources
- pkg:maven/com.tencent.polaris/stat-prometheus@1.1.1
- pkg:maven/com.tencent.polaris/stat-prometheus@1.1.1?classifier=sources
