- pkg:maven/run.mone/prometheus-trace-etl@0.0.6-jdk21
- pkg:maven/run.mone/prometheus-trace-etl@0.0.6-jdk21?classifier=sources
- pkg:maven/run.mone/prometheus-trace-etl@1.6.1-jdk21
- pkg:maven/run.mone/prometheus-trace-etl@1.6.1-jdk21?classifier=sources
