- pkg:maven/org.apache.flink/flink-connector-prometheus-request-signer-amp@1.0.0-1.19
- pkg:maven/org.apache.flink/flink-connector-prometheus-request-signer-amp@1.0.0-1.19?classifier=sources
- pkg:maven/org.apache.flink/flink-connector-prometheus-request-signer-amp@1.0.0-1.20
- pkg:maven/org.apache.flink/flink-connector-prometheus-request-signer-amp@1.0.0-1.20?classifier=sources
