- pkg:maven/nl.mirila.metrics/mirila-metrics-prometheus@1.1.2
- pkg:maven/nl.mirila.metrics/mirila-metrics-prometheus@1.1.2?classifier=sources
- pkg:maven/nl.mirila.metrics/mirila-metrics-prometheus@1.1.3
- pkg:maven/nl.mirila.metrics/mirila-metrics-prometheus@1.1.3?classifier=sources
- pkg:maven/nl.mirila.metrics/mirila-metrics-prometheus@1.4.0
- pkg:maven/nl.mirila.metrics/mirila-metrics-prometheus@1.4.0?classifier=sources
