- pkg:maven/io.prometheus/prometheus-metrics-exposition-formats-no-protobuf@1.3.7?classifier=sources
- pkg:maven/io.prometheus/prometheus-metrics-exposition-formats-no-protobuf@1.3.8?classifier=sources
